server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp1?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
api:
  prefix: /api/v1
jwt:
  expiration: 2592000 # 30 days = 2592000 seconds
  secretKey: P6x9zqndeqC/Es1ICXvYJmx9BqK/AogTrpVy8LwkjIY=